name: bigdata-cassandra
services:

  backend:
    container_name: bigdata-be-cassandra
    restart: always
    ports:
      - 5001:5001
    build:
      context: ./backend-node
      dockerfile: ./Dockerfile
    environment:
      DB: "cassandra"
    volumes:
      - ./backend-node:/code
    networks:
      - main
    

  frontend:
    container_name: bigdata-fe-cassandra
    restart: always
    ports:
      - 4200:4200
    build:
      context: ./frontend
      dockerfile: ./Dockerfile

  cassandra-1:
    image: "cassandra:latest"  # cassandra:4.1.3
    container_name: "bigdata-cassandra-1"
    ports:
      - 7000:7000
      - 9042:9042
    networks:
      - main
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=auto  # default, use IP addr of container # = CASSANDRA_BROADCAST_ADDRESS
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
    volumes:
      - cassandra-node-1:/var/lib/cassandra:rw
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3
  
  cassandra-2:
    image: "cassandra:latest"  # cassandra:4.1.3
    container_name: "bigdata-cassandra-2"
    ports:
      - 9043:9042
    networks:
      - main
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=auto  # default, use IP addr of container # = CASSANDRA_BROADCAST_ADDRESS
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_SEEDS=cassandra-1
    depends_on:
      cassandra-1:
        condition: service_healthy
    volumes:
      - cassandra-node-2:/var/lib/cassandra:rw
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3

  cassandra-web:
    image: ipushc/cassandra-web:latest
    container_name: cassandra-web-infint
    ports:
      - 8083:8083
    environment:
      - CASSANDRA_HOST=cassandra-1
      - CASSANDRA_PORT=9042
      - CASSANDRA_USERNAME=admin
      - CASSANDRA_PASSWORD=admin
    restart: always
    depends_on:
      - cassandra-2
    networks:
      - main

volumes:
  cassandra-node-1:
  cassandra-node-2:
networks:
  main:
    driver: bridge
