version: '3'

services:

  backend:
    container_name: backend
    restart: always
    ports:
      - 5001:5001
    build:
      context: ./backend-node
      dockerfile: ./Dockerfile
    volumes:
      - ./backend-node:/code
    networks:
      - main

  cassandra-1:
    image: cassandra:latest
    container_name: cassandra-1
    ports:
      - 7000:7000
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=auto  # default, use IP addr of container # = CASSANDRA_BROADCAST_ADDRESS
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=my-datacenter-1
    volumes:
      - cassandra-data-1:/var/lib/cassandra
    networks:
      - main
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3

  cassandra-2:
    image: cassandra:latest
    container_name: cassandra-2
    ports:
      - 9043:9042
    environment:
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=auto  # default, use IP addr of container # = CASSANDRA_BROADCAST_ADDRESS
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=my-datacenter-1
      - CASSANDRA_SEEDS=cassandra-1
    depends_on:
      cassandra-1:
        condition: service_healthy
    volumes:
      - cassandra-data-2:/var/lib/cassandra
    networks:
      - main
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3

  cassandra-3:
    image: cassandra:latest
    container_name: cassandra-3
    ports:
      - 9044:9042
    environment:
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=auto  # default, use IP addr of container # = CASSANDRA_BROADCAST_ADDRESS
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=my-datacenter-1
      - CASSANDRA_SEEDS=cassandra-1
    depends_on:
      cassandra-2:
        condition: service_healthy
    volumes:
      - cassandra-data-3:/var/lib/cassandra
    networks:
      - main
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3
  

  cassandra-web:
    image: ipushc/cassandra-web:latest
    container_name: cassandra-web
    ports:
      - 8083:8083
    environment:
      - CASSANDRA_HOST=cassandra-1
      - CASSANDRA_PORT=9042
    restart: always
    depends_on:
      - cassandra-3
    networks:
      - main

volumes:
  cassandra-data-1:
  cassandra-data-2:
  cassandra-data-3:

networks:
  main:
    driver: bridge
